// MT options copied straight from the MT
// TODO: format?

export const materialOptions = [
  {
    id: 'puu',
    order: 10,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'maa_ainekset',
    order: 20,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'betoni',
    order: 30,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'tiilet_ja_keramiikka',
    order: 40,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'paperi',
    order: 50,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kartonki',
    order: 60,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'muovi',
    order: 70,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kumi',
    order: 80,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'metalli',
    order: 90,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'lasi',
    order: 100,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kipsi',
    order: 110,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'asbesti',
    order: 120,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'eristeet',
    order: 130,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'asfaltti_ja_bitumi',
    order: 140,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'tekstiili',
    order: 150,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'biojate',
    order: 160,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'elintarvikesivuvirta',
    order: 170,
    isWaste: false,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'lanta',
    order: 180,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'elainperainen_orgaaninen_materiaali_ei_lanta',
    order: 190,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kasviperainen_orgaaninen_materiaali',
    order: 200,
    isWaste: true,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'liete_pesu_ja_jatevedet',
    order: 210,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'tuhka',
    order: 220,
    isWaste: true,
    isMaterial: true,
  },
  {
    id: 'kuona',
    order: 230,
    isWaste: true,
    isMaterial: true,
  },
  {
    id: 'polyt_ja_sakat',
    order: 240,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'maalit_ja_lakat',
    order: 250,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'laakkeet',
    order: 260,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kemikaalit',
    order: 270,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'epakurantit_tuotteet',
    order: 280,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'katalyytit',
    order: 290,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'oljy_emulsio_ja_muut_oljyiset_jatteet',
    order: 300,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'akut_ja_paristot',
    order: 310,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'renkaat',
    order: 320,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'sahko_ja_elektroniikkaromu',
    order: 330,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'sekalainen_rakennus_ja_purkujate',
    order: 340,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'sekalainen_yhdyskunta_jate',
    order: 350,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'jatepolttoaine',
    order: 360,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'mekaanisen_kasittelyn_rejektit',
    order: 370,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kayttokelvottomat_suurikokoiset_esineet',
    order: 380,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'kayttokelpoiset_huonekalut',
    order: 390,
    isWaste: false,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'rakennusosat',
    order: 400,
    isWaste: false,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'muu_teollisuusjate',
    order: 410,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'muu_jate',
    order: 420,
    isWaste: true,
    isMaterial: false,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
  {
    id: 'muu_sivuvirta',
    order: 430,
    isWaste: false,
    isMaterial: true,
    configurationType: 'MaterialType',
    subMaterialTypes: [],
  },
];

export const unitOptions = [
  {
    id: 'kg',
    order: 10,
    configurationType: 'UnitType',
  },
  {
    id: 't',
    order: 20,
    configurationType: 'UnitType',
  },
  {
    id: 'm',
    order: 30,
    configurationType: 'UnitType',
  },
  {
    id: 'm2',
    order: 40,
    configurationType: 'UnitType',
  },
  {
    id: 'm3',
    order: 50,
    configurationType: 'UnitType',
  },
  {
    id: 'kpl',
    order: 60,
    configurationType: 'UnitType',
  },
];

export const industryOptions = [
  {
    id: 'rakentaminen_ja_purkaminen',
    order: 10,
    configurationType: 'IndustryType',
  },
  {
    id: 'jate_vesi_ja_jatevesihuolto',
    order: 20,
    configurationType: 'IndustryType',
  },
  {
    id: 'kaivannaisteollisuus',
    order: 30,
    configurationType: 'IndustryType',
  },
  {
    id: 'elintarviketeollisuus',
    order: 35,
    configurationType: 'IndustryType',
  },
  {
    id: 'maa_metsa_ja_kalatalous',
    order: 40,
    configurationType: 'IndustryType',
  },
  {
    id: 'puu_paperi_ja_kartonkiteollisuus',
    order: 50,
    configurationType: 'IndustryType',
  },
  {
    id: 'nahka_turkis_ja_tekstiiliteollisuus',
    order: 60,
    configurationType: 'IndustryType',
  },
  {
    id: 'petrokemianteollisuus',
    order: 70,
    configurationType: 'IndustryType',
  },
  {
    id: 'kemianteollisuus',
    order: 80,
    configurationType: 'IndustryType',
  },
  {
    id: 'valokuvateollisuus',
    order: 85,
    configurationType: 'IndustryType',
  },
  {
    id: 'metalliteollisuus',
    order: 90,
    configurationType: 'IndustryType',
  },
  {
    id: 'energiantuotanto',
    order: 100,
    configurationType: 'IndustryType',
  },
  {
    id: 'muu_teollisuus',
    order: 110,
    configurationType: 'IndustryType',
  },
  {
    id: 'tukku_ja_vahittaiskauppa',
    order: 120,
    configurationType: 'IndustryType',
  },
  {
    id: 'ravitsemus_ja_majoituspalvelut',
    order: 130,
    configurationType: 'IndustryType',
  },
  {
    id: 'terveydenhuolto',
    order: 140,
    configurationType: 'IndustryType',
  },
  {
    id: 'kotitaloudet_toimistot_koulut_paivakodit_ja_vastaavat',
    order: 150,
    configurationType: 'IndustryType',
  },
  {
    id: 'muu_toimiala',
    order: 160,
    configurationType: 'IndustryType',
  },
];
