# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm install --global mocha
      - run: npm install --global chai
      - run: npm install --global ts-node
      - run: npm run check
      - run: npm run test
      - uses: phoenix-actions/test-reporting@v8
        id: test-report                     # Set ID reference for step
        with:
          artifact: ''            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: 'reports/jest-junit.xml'                     # Path to test results (inside artifact .zip)
          reporter: mocha-json 
          fail-on-error: 'true'
